//USERS
export const GOOGLE_SIGIN = 'GOOGLE_SIGIN'
export const FB_SIGNIN = 'FB_SIGNIN'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT'

//LOCATION
export const UPDATE_POSITION = 'UPDATE_POSITION'
export const SEARCH_GOOGLE_PLACE = 'SEARCH_GOOGLE_PLACE'
export const CHANGE_MAPTYPE = 'CHANGE_MAPTYPE'