//USERS
export const GOOGLE_SIGIN = 'GOOGLE_SIGIN'
export const FB_SIGNIN = 'FB_SIGNIN'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT'
export const CHECK_LOGIN = 'CHECK_LOGIN'

//LOCATION
export const UPDATE_POSITION = 'UPDATE_POSITION'
export const SEARCH_GOOGLE_PLACE = 'SEARCH_GOOGLE_PLACE'
export const SEARCH_GOOGLE_PLACE_MEETUP = 'SEARCH_GOOGLE_PLACE_MEETUP'
export const CHANGE_MAPTYPE = 'CHANGE_MAPTYPE'
export const TOGGLE_DIRECTION = 'TOGGLE_DIRECTION'
export const CLOSE_DIRECTION = 'CLOSE_DIRECTION'